---
layout: single
classes: wide
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
header:
  overlay_image: /assets/images/Header.jpg
---
remote_theme: DustinRogers/minimal-mistakes

